In [5]:
import numpy as np
from scipy.optimize import minimize

In [6]:
def rosen(x):
    #...     """The Rosenbrock function"""
    return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)

In [52]:
x0 = np.array([.7,0.9,0.7,.8,1.2,1.3,.6,1.2])
res = minimize(rosen, x0, method='nelder-mead',options={'xtol': 1e-8, 'disp': True})
print(res.x)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 973
         Function evaluations: 1466
[ 1.          1.          1.          1.          1.          1.
  0.99999999  0.99999999]


In [53]:
x0 = np.array([.7,20,0.7,5,100,1.3,.6,1.7])
res = minimize(rosen, x0, method='Powell',options={'xtol': 1e-8, 'disp': True})
print(res.x)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 44
         Function evaluations: 5621
[ 1.  1.  1.  1.  1.  1.  1.  1.]


In [54]:
x0 = np.array([.7,20,0.7,5,100,1.3,.6,1.7])
res = minimize(rosen, x0, method='CG',options={'xtol': 1e-8, 'disp': True})
print(res.x)

C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\ipykernel_launcher.py:2: OptimizeWarning: Unknown solver options: xtol
  


Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 76
         Function evaluations: 1580
         Gradient evaluations: 158
[ 0.99999991  0.99999981  0.99999966  0.99999938  0.99999881  0.99999767
  0.99999536  0.99999073]


In [55]:
x0 = np.array([.7,20,0.7,5,100,1.3,.6,1.7])
res = minimize(rosen, x0, method='BFGS',options={'xtol': 1e-8, 'disp': True})
print(res.x)

C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\ipykernel_launcher.py:2: OptimizeWarning: Unknown solver options: xtol
  


Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 170
         Function evaluations: 1910
         Gradient evaluations: 191
[ 0.99999988  0.99999976  0.99999956  0.99999915  0.99999832  0.99999667
  0.99999335  0.99998669]


In [58]:
x0 = np.array([.7,20,0.7,5,100,1.3,.6,1.7])
res = minimize(rosen, x0, method='L-BFGS-B',options={'xtol': 1e-8, 'disp': True})
print(res.x)

[ 0.99999994  0.99999976  0.99999961  0.9999992   0.99999842  0.9999969
  0.99999373  0.99998727]


C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\ipykernel_launcher.py:2: OptimizeWarning: Unknown solver options: xtol
  


In [59]:
x0 = np.array([.7,20,0.7,5,100,1.3,.6,1.7])
res = minimize(rosen, x0, method='TNC',options={'xtol': 1e-8, 'disp': True})
print(res.x)

[ 1.00229172  1.00534723  1.01175171  1.0216662   1.04411688  1.08758734
  1.18162085  1.3962443 ]


In [61]:
x0 = np.array([.7,20,0.7,5,100,1.3,.6,1.7])
res = minimize(rosen, x0, method='SLSQP',options={'xtol': 1e-8, 'disp': True})
print(res.x)

Iteration limit exceeded    (Exit mode 9)
            Current function value: 2.2680988258391332
            Iterations: 101
            Function evaluations: 1056
            Gradient evaluations: 101
[ 0.96929621  0.94353039  0.88077158  0.77552328  0.57226411  0.25839456
  0.06537506  0.01829352]


C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\ipykernel_launcher.py:2: OptimizeWarning: Unknown solver options: xtol
  


In [66]:
x0 = np.array([.7,20,0.7,5,100,1.3,.6,1.7])
res = minimize(rosen, x0, method='custom',options={'xtol': 1e-8, 'disp': True})
print(res.x)

ValueError: Unknown solver custom

In [44]:
print(res.x)

[ 1.          1.          1.          1.          1.          1.
  0.99999999  0.99999999]


In [23]:
print(x0)

[ 1.3  0.7  0.8  1.9  1.2  7. ]


In [28]:
print(x0[3:])

[ 1.9  1.2  7. ]


In [29]:
print(x0[:-1])

[ 1.3  0.7  0.8  1.9  1.2]


In [30]:
print(x0[:-2])

[ 1.3  0.7  0.8  1.9]
